### PR TITLE
Introduce SprogApiClient to handle downloading of poems

### PR DESCRIPTION
**Pull request by adamhaafiz**
Cleaned up the project structure by breaking up the files into their respective packages. App now uses Volley to fetch the poems file instead of DownloadManager.

### CODE REVIEW

**Comment by PaulKlinger** [comment]
What's the advantage of using volley instead of DownloadManager? 

I guess one advantage could be storing the json in the internal directory and getting rid of the WRITE_EXTERNAL_STORAGE permission, but you lose the automatic progress display in the notification. DownloadManager also automatically resumes the download if the network connection is interrupted in the middle.

**Comment by adamhaafiz** [comment]
I don't think DownloadManager was the right approach to take in the first place. If you're dealing with APIs (especially ones that return you JSON data!), Volley is much more suited for the task. One immediate benefit you'll gain is that the response is returned to you as a `JSONArray` object, which makes the job of parsing the JSON object much easier.

I haven't gotten around to writing the full code, but using this approach you could probably eliminate the entire [PoemParser.java](https://github.com/PaulKlinger/Sprog-App/blob/master/app/src/main/java/com/almoturg/sprog/PoemParser.java) file into something like this:
```java
public void onResponse(JSONArray response) {
    Bypass bypass = new Bypass(mContext, new Bypass.Options());
    List<Poem> poems = new ArrayList<>();

    for (int i = 0; i < response.length(); i++) {
        JSONObject json = response.optJSONObject(i);

        Poem poem = new Poem();
        poem.gold = json.optInt("gold");
        poem.score = json.optInt("score");
        poem.link = json.optString("link");
        poem.content = json.optString("orig_content").replace("^", "");
        poem.first_line = bypass.markdownToSpannable(
                poem.content.trim().split("\n", 2)[0].trim() + "...");
        poem.timestamp = json.optDouble("timestamp");
        poem.post_title = json.optString("submission_title");
        poem.post_author = "/u/" + json.optString("submission_user").replace("\\_",
                "_");
        poem.post_content = json.optString("orig_submission_content").replace("^", "");
        poem.main_poem = mMainPoemLinks.get(poem.link);

        List<ParentComment> parents = new ArrayList<>();
        JSONArray parentsJson = json.optJSONArray("parents");

        for (int j = 0; j < parentsJson.length(); j++) {
            JSONObject parentJson = parentsJson.optJSONObject(j);

            ParentComment parentComment = new ParentComment();
            // perform parsing of parent
            parents.add(parentComment);
        }

        poem.parents = parents;
        poems.add(poem);
    }

    listener.onComplete(poems, null);
}
```

This is a lot more readable and more maintainable should there ever be any changes to the JSON data returned from the API.

**Comment by PaulKlinger** [comment]
I really don't want to make the user experience worse just to make the code nicer. But implementing retrying and automatic resuming when the connection is interrupted seems a bit like reinventing the wheel. (The automatic resuming is actually useful, e.g. when I just walk around at home my phone switches between two wifi access points and interrupts the connection.)

Anyway, when it's not time to update the poems they have to be loaded from the local file anyway. So if the performance using JsonArray is the same or better as with JsonReader that could be an option even if the json is downloaded using DownloadManager. I originally used JsonReader because the file is relatively large and a streaming parser should be faster (or at least use less memory), but it's possible that doesn't make any difference anymore. That definitely needs testing on low-end devices though.

**Comment by adamhaafiz** [comment]
Thanks for opening my mind and making me realise some things that I had not considered before! Those are very good reasons to avoid making this change to the application. Guess I've still got a lot to learn!

**Pull request closed without merging**
